### ISSUE TITLE
Test project

### ISSUE THREAD

**Issue by xptosoft** [gandalf15/CS4040#1]
Marcel,
Can you please share the code used to test both frameworks ?

**Comment by gandalf15** [comment]
Hi xptosoft!
I am sorry but I was unable to find the source code. I was doing this report for my one course at my University and I did not save the source code. It's been 4 years ago. I would know better know. Sorry about this. I hope that the report could help you at least a bit.

**Comment by gandalf15** [comment]
BTW check this page: https://www.eprosima.com/index.php/resources-all/performance 
they have nice performance comparisons.

**Comment by xptosoft** [comment]
Thanks!
